- name: Safe package removal (Ubuntu + Amazon Linux)
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    ubuntu_packages:
      - nginx
      - mysql-server

    amazon_packages:
      - nginx
      - mariadb-server

  tasks:

    - name: Stop services first
      service:
        name: "{{ item }}"
        state: stopped
      loop:
        - nginx
        - mysql
        - mariadb
      ignore_errors: yes

    - name: Remove packages on Ubuntu (with purge)
      apt:
        name: "{{ ubuntu_packages }}"
        state: absent
        purge: yes
        autoremove: yes
      when: ansible_os_family == "Debian"

    - name: Remove packages on Amazon Linux
      yum:
        name: "{{ amazon_packages }}"
        state: absent
      when: ansible_os_family == "RedHat"
